// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_24BIR-TfTK_W795gobZonD7PesvZV-A',
    appId: '1:821539417839:android:d2aa04dcea9f9d6967b51a',
    messagingSenderId: '821539417839',
    projectId: 'page-penner',
    databaseURL: 'https://page-penner-default-rtdb.firebaseio.com',
    storageBucket: 'page-penner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxiHHEhO6ENKeC1PyGOKpToJrzBanspo',
    appId: '1:821539417839:ios:2328a394202ec33667b51a',
    messagingSenderId: '821539417839',
    projectId: 'page-penner',
    databaseURL: 'https://page-penner-default-rtdb.firebaseio.com',
    storageBucket: 'page-penner.appspot.com',
    androidClientId: '821539417839-f7vsie6tm8ruco7pp230o78gs36rvnb5.apps.googleusercontent.com',
    iosClientId: '821539417839-9pa2dun89ddfjhmkn6p55jd5uuu9bqls.apps.googleusercontent.com',
    iosBundleId: 'com.pagepenner.pagePenner',
  );
}
